export const hotelTypes = [
    "Beach Resort",
    "Motel",
    "Family",
    "Business",
    "Boutique",
    "Luxury",
    "Budget",
    "All-Inclusive",
    "Spa",
    "Ski Resort",
    "Airport",
    "Extended Stay",
    "Bed and Breakfast",
    "Inn",
    "Villa",
    "Hostel",
    "Vacation Rental",
    "Golf Resort",
    "Casino",
    "Heritage",
    "Eco-Friendly",
    "Wellness",
    "Apartment",
    "Convention",
    "City",
    "Mountain Lodge",
    "Desert Resort",
    "Lakeside",
    "Pet-Friendly",
    "Adult-Only"
  ];

  export const hotelFacilities = [
  "Free WiFi",
  "Free Parking",
  "Paid Parking",
  "Family Rooms",
  "Swimming Pool",
  "Fitness Center",
  "Restaurant",
  "Room Service",
  "Bar/Lounge",
  "Spa",
  "Airport Shuttle",
  "Business Center",
  "Conference Rooms",
  "Pet Friendly",
  "Breakfast Included",
  "Air Conditioning",
  "24-Hour Front Desk",
  "Concierge Service",
  "Laundry Service",
  "Housekeeping",
  "Luggage Storage",
  "Hot Tub/Jacuzzi",
  "Beach Access",
  "Kids Club",
  "Childcare",
  "Disability Access",
  "Non-Smoking Rooms",
  "Coffee/Tea in Lobby",
  "Valet Parking",
  "Electric Vehicle Charging"
];